# Questions::Generate::English::GenerateHomophonesQuestionsJob.perform_now
class Questions::Generate::English::GenerateHomophonesQuestionsJob < ApplicationJob
  queue_as :default

  def perform(questions_to_generate = 10)
    questions = []
    homophones.take(questions_to_generate).each do |pair|
      questions <<
        {
          question: pair.first,
          answer: pair.last
        }
    end
    questions
  end

  private

  def homophones
    @homophones = [
      ["accept", "except"],
      ["aisle", "isle"],
      ["allowed", "aloud"],
      ["alter", "altar"],
      ["arc", "ark"],
      ["ascent", "assent"],
      ["aural", "oral"],
      ["bail", "bale"],
      ["bare", "bear"],
      ["baron", "barren"],
      ["bawd", "board"],
      ["be", "bee"],
      ["beach", "beech"],
      ["bean", "been"],
      ["beat", "beet"],
      ["berth", "birth"],
      ["bite", "byte"],
      ["blew", "blue"],
      ["bough", "bow"],
      ["brake", "break"],
      ["bread", "bred"],
      ["buy", "by"],
      ["cell", "sell"],
      ["cent", "scent"],
      ["cereal", "serial"],
      ["chili", "chilly"],
      ["choir", "quire"],
      ["coarse", "course"],
      ["colonel", "kernel"],
      ["complement", "compliment"],
      ["council", "counsel"],
      ["creak", "creek"],
      ["dear", "deer"],
      ["dew", "due"],
      ["die", "dye"],
      ["discreet", "discrete"],
      ["doe", "dough"],
      ["dual", "duel"],
      ["earn", "urn"],
      ["eye", "I"],
      ["faint", "feint"],
      ["fair", "fare"],
      ["fir", "fur"],
      ["flour", "flower"],
      ["for", "four"],
      ["forth", "fourth"],
      ["gait", "gate"],
      ["groan", "grown"],
      ["guessed", "guest"],
      ["hail", "hale"],
      ["hair", "hare"],
      ["hall", "haul"],
      ["heal", "heel"],
      ["hear", "here"],
      ["hi", "high"],
      ["hoard", "horde"],
      ["hole", "whole"],
      ["idle", "idol"],
      ["it's", "its"],
      ["knight", "night"],
      ["knot", "not"],
      ["know", "no"],
      ["lead", "led"],
      ["leak", "leek"],
      ["loan", "lone"],
      ["made", "maid"],
      ["mail", "male"],
      ["main", "mane"],
      ["meat", "meet"],
      ["medal", "meddle"],
      ["mind", "mined"],
      ["missed", "mist"],
      ["moan", "mown"],
      ["morning", "mourning"],
      ["none", "nun"],
      ["one", "won"],
      ["pair", "pare"],
      ["palate", "palette"],
      ["peace", "piece"],
      ["plain", "plane"],
      ["practice", "practise"],
      ["principal", "principle"],
      ["profit", "prophet"],
      ["rain", "reign"],
      ["read", "reed"],
      ["right", "write"],
      ["road", "rode"],
      ["role", "roll"],
      ["root", "route"],
      ["sail", "sale"],
      ["scene", "seen"],
      ["sea", "see"],
      ["seam", "seem"],
      ["sew", "so"],
      ["shoe", "shoo"],
      ["sight", "site"],
      ["soar", "sore"],
      ["sole", "soul"],
      ["some", "sum"],
      ["son", "sun"],
      ["stair", "stare"],
      ["stationary", "stationery"],
      ["steal", "steel"],
      ["suite", "sweet"],
      ["tail", "tale"],
      ["their", "there"],
      ["threw", "through"],
      ["thyme", "time"],
      ["toe", "tow"],
      ["vain", "vein"],
      ["vale", "veil"],
      ["vial", "vile"],
      ["waist", "waste"],
      ["wait", "weight"],
      ["way", "weigh"],
      ["weak", "week"],
      ["wear", "where"],
      ["weather", "whether"],
      ["which", "witch"],
      ["who's", "whose"],
      ["wood", "would"],
      ["yew", "you"],
      ["your", "you're"]
    ].sort_by { rand }
  end
end
